#ifndef BLUETOOTHPLUGIN_GLOBAL_H
#define BLUETOOTHPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>
#define BLUETOOTHPLUGIN_LIBRARY

#if defined(BLUETOOTHPLUGIN_LIBRARY)
#  define BLUETOOTHPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLUETOOTHPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif